services:
  dev:
    ipc: host
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=wayland # Lub xcb, co tam wolisz na AMD
      - XDG_RUNTIME_DIR=/run/user/1000
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-wayland-1}
      
    volumes:
      - .:/app
      - /run/user/1000:/run/user/1000:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri
