# compose-windows.yml 

services:
  dev:
    # ...
    environment:
      DISPLAY: host.docker.internal:0.0  # To zazwyczaj wystarcza na Windowsie
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "all"

    # TO JEST KLUCZ DLA WINDOWSA:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]