services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.nvidia
      target: base

    command: sleep infinity

    privileged: true
    ipc: host

    environment:
      DISPLAY: host.docker.internal:0.0
      QT_QPA_PLATFORM: xcb
      QT_XCB_GL_INTEGRATION: xcb_glx
      QSG_RHI_BACKEND: opengl
      QSG_RENDER_LOOP: basic
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,graphics,display

    volumes:
      - .:/app
      - /dev/dri:/dev/dri

    stdin_open: true
    tty: true